
version: '3.9'
services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  node:
    image: node:18
    working_dir: /home/node/app
    user: node
    depends_on:
      - postgres
    volumes:
      - $PWD/:/home/node/app
      - $PWD/.cache/npm:/root/.npm
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    
volumes:
  db:
    driver: local